package index

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/gbuehler/lore/internal/pathutil"
)

// PageEntry holds extracted metadata from a single markdown page.
type PageEntry struct {
	RelPath    string // e.g. "Services/gateway.md"
	Name       string // filename without .md
	EntityType string
	Aliases    string
}

// BuildLibraryIndex generates Wiki/index.md for a library by scanning all
// pages under Wiki/, extracting frontmatter metadata, and producing a
// navigable table grouped by subdirectory.
func BuildLibraryIndex(libPath string) error {
	wikiDir := filepath.Join(libPath, "Wiki")
	info, err := os.Stat(wikiDir)
	if err != nil || !info.IsDir() {
		return fmt.Errorf("no Wiki/ directory in %s", libPath)
	}

	// Collect all .md files under Wiki/, excluding index.md itself
	var pages []PageEntry
	filepath.Walk(wikiDir, func(path string, fi os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if fi.IsDir() && strings.HasPrefix(fi.Name(), ".") {
			return filepath.SkipDir
		}
		if fi.IsDir() || !strings.HasSuffix(fi.Name(), ".md") {
			return nil
		}
		if fi.Name() == "index.md" {
			return nil
		}

		rel, _ := filepath.Rel(wikiDir, path)
		name := strings.TrimSuffix(fi.Name(), ".md")
		entityType, aliases := extractFrontmatterFields(path)

		pages = append(pages, PageEntry{
			RelPath:    rel,
			Name:       name,
			EntityType: entityType,
			Aliases:    aliases,
		})
		return nil
	})

	// Group by subdirectory
	groups := make(map[string][]PageEntry)
	for _, p := range pages {
		dir := filepath.Dir(p.RelPath)
		if dir == "." {
			dir = "(root)"
		}
		groups[dir] = append(groups[dir], p)
	}

	// Sort group names, sort pages within each group
	var groupNames []string
	for g := range groups {
		groupNames = append(groupNames, g)
	}
	sort.Strings(groupNames)
	for _, g := range groupNames {
		sort.Slice(groups[g], func(i, j int) bool {
			return groups[g][i].Name < groups[g][j].Name
		})
	}

	// Generate index
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("last_updated: %s\n", time.Now().Format("2006-01-02")))
	b.WriteString("---\n")
	b.WriteString("# Library Index\n\n")
	b.WriteString(fmt.Sprintf("Auto-generated by `lore index`. %d pages total.\n\n", len(pages)))

	for _, g := range groupNames {
		entries := groups[g]
		if g == "(root)" {
			b.WriteString("## Pages\n\n")
		} else {
			b.WriteString(fmt.Sprintf("## %s\n\n", g))
		}

		b.WriteString("| Page | Type | Aliases |\n")
		b.WriteString("|---|---|---|\n")
		for _, p := range entries {
			b.WriteString(fmt.Sprintf("| [%s](%s) | %s | %s |\n", p.Name, p.RelPath, p.EntityType, p.Aliases))
		}
		b.WriteString("\n")
	}

	indexPath := filepath.Join(wikiDir, "index.md")
	if err := pathutil.AtomicWriteFile(indexPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("writing index: %w", err)
	}
	return nil
}

// extractFrontmatterFields reads entity_type and aliases from YAML frontmatter.
func extractFrontmatterFields(path string) (entityType, aliases string) {
	f, err := os.Open(path)
	if err != nil {
		return "", ""
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)

	// First line must be ---
	if !scanner.Scan() || strings.TrimSpace(scanner.Text()) != "---" {
		return "", ""
	}

	for scanner.Scan() {
		line := scanner.Text()
		if strings.TrimSpace(line) == "---" {
			break
		}

		if strings.HasPrefix(line, "entity_type:") {
			entityType = strings.TrimSpace(strings.TrimPrefix(line, "entity_type:"))
		}
		if strings.HasPrefix(line, "type:") && entityType == "" {
			entityType = strings.TrimSpace(strings.TrimPrefix(line, "type:"))
		}
		if strings.HasPrefix(line, "aliases:") {
			val := strings.TrimSpace(strings.TrimPrefix(line, "aliases:"))
			// Inline list: ["a", "b"]
			val = strings.TrimPrefix(val, "[")
			val = strings.TrimSuffix(val, "]")
			val = strings.ReplaceAll(val, "\"", "")
			val = strings.TrimSpace(val)
			aliases = val
		}
	}
	return entityType, aliases
}
